version: "3.9"
services:
  maiz-amigo-demo:
    container_name: maiz-amigo-demo
    ports:
      - "8588:80"
    build:
      context: ./
      dockerfile: .docker/dockerfile
    restart: unless-stopped
